"""
Data augmentation for Raman spectra.
Reads the non-augmented parquet file generated by previous steps, applies a set
of augmentation transforms to spectra of non-healthy teeth, and saves the
result as a new parquet file.

Expected input file
-----------------
- scans_nonaugmented.parquet  (raw, has Wavenumbers/Intensities columns)

Expected output file
-----------------
- scans_augmented.parquet     (raw, has Wavenumbers/Intensities columns and augmentation_type column)

Notes
-----
- The script will automatically skip processing if the output file already exists.
- The augmentation process includes:
  1. Adding Gaussian noise to intensity values.
  2. Adding sinusoidal baseline drift to intensity values.
  3. Scaling intensity values by a random multiplicative factor.
  4. Shifting a spectrum along the wavenumber axis.
  5. Broadening spectrum peaks using a Gaussian filter.
"""

import os
import numpy as np
import pandas as pd
from scipy.interpolate import interp1d
from scipy.ndimage import gaussian_filter1d
from ..Utils.utils import find_project_root

GLOBAL_SEED = 42




def add_noise(intensity, rng, noise_std=0.01):
    """Add Gaussian noise to intensity values.

    Parameters
    ----------
    intensity : numpy.ndarray
        Intensity values.
    rng : numpy.random.Generator
        Random generator used for reproducibility.
    noise_std : float, default=0.01
        Standard deviation of the Gaussian noise.

    Returns
    -------
    numpy.ndarray
        Noisy intensity values.
    """
    return intensity + rng.normal(0, noise_std, size=intensity.shape)


def baseline_drift(wavenumbers, intensity, rng, drift_scale=0.02):
    """Add sinusoidal baseline drift to intensity values.

    Parameters
    ----------
    wavenumbers : numpy.ndarray
        Wavenumber axis values.
    intensity : numpy.ndarray
        Intensity values.
    rng : numpy.random.Generator
        Random generator used for reproducibility.
    drift_scale : float, default=0.02
        Amplitude scale of the drift component.

    Returns
    -------
    numpy.ndarray
        Intensity values with added baseline drift.
    """
    freq = rng.uniform(0.5, 2)
    drift = drift_scale * np.sin(
        wavenumbers / wavenumbers.max() * 2 * np.pi * freq
    )
    return intensity + drift


def scale_intensity(intensity, rng, scale_range=(0.9, 1.1)):
    """Scale intensity values by a random multiplicative factor.

    Parameters
    ----------
    intensity : numpy.ndarray
        Intensity values.
    rng : numpy.random.Generator
        Random generator used for reproducibility.
    scale_range : tuple[float, float], default=(0.9, 1.1)
        Inclusive range for the sampled scale factor.

    Returns
    -------
    numpy.ndarray
        Scaled intensity values.
    """
    scale = rng.uniform(*scale_range)
    return intensity * scale


def shift_spectrum(wavenumbers, intensity, rng, shift_range=(-3, 3)):
    """Shift a spectrum along the wavenumber axis.

    Parameters
    ----------
    wavenumbers : numpy.ndarray
        Wavenumber axis values.
    intensity : numpy.ndarray
        Intensity values.
    rng : numpy.random.Generator
        Random generator used for reproducibility.
    shift_range : tuple[float, float], default=(-3, 3)
        Range for the sampled shift in wavenumber units.

    Returns
    -------
    numpy.ndarray
        Intensity values sampled on the original axis after shifting.
    """
    shift = rng.uniform(*shift_range)
    f = interp1d(
        wavenumbers + shift,
        intensity,
        bounds_error=False,
        fill_value="extrapolate",
    )
    return f(wavenumbers)


def broaden_peaks(intensity, rng, sigma_range=(0.5, 2.0)):
    """Broaden spectrum peaks using a Gaussian filter.

    Parameters
    ----------
    intensity : numpy.ndarray
        Intensity values.
    rng : numpy.random.Generator
        Random generator used for reproducibility.
    sigma_range : tuple[float, float], default=(0.5, 2.0)
        Range for the Gaussian filter sigma.

    Returns
    -------
    numpy.ndarray
        Broadened intensity values.
    """
    sigma = rng.uniform(*sigma_range)
    return gaussian_filter1d(intensity, sigma)


def kumaraswamy_warp(wavenumbers, intensity, rng, a_range=(0.8, 2.0), b_range=(0.8, 2.0)):
    """Warp wavenumbers with a Kumaraswamy transform and resample intensity.

    Parameters
    ----------
    wavenumbers : numpy.ndarray
        Wavenumber axis values.
    intensity : numpy.ndarray
        Intensity values.
    rng : numpy.random.Generator
        Random generator used for reproducibility.
    a_range : tuple[float, float], default=(0.8, 2.0)
        Sampling range for the Kumaraswamy `a` parameter.
    b_range : tuple[float, float], default=(0.8, 2.0)
        Sampling range for the Kumaraswamy `b` parameter.

    Returns
    -------
    numpy.ndarray
        Intensity values corresponding to warped wavenumbers.
    """
    a = rng.uniform(*a_range)
    b = rng.uniform(*b_range)

    wn_norm = (wavenumbers - wavenumbers.min()) / (
        wavenumbers.max() - wavenumbers.min()
    )

    warped_norm = 1 - (1 - wn_norm ** a) ** b
    warped_wn = wavenumbers.min() + warped_norm * (
        wavenumbers.max() - wavenumbers.min()
    )

    f = interp1d(
        wavenumbers,
        intensity,
        bounds_error=False,
        fill_value="extrapolate",
    )

    return f(warped_wn)


def augment_spectrum(wavenumbers, intensity, base_seed):
    """Apply all augmentation transforms to a single spectrum.

    Parameters
    ----------
    wavenumbers : numpy.ndarray
        Wavenumber axis values.
    intensity : numpy.ndarray
        Intensity values.
    base_seed : int
        Seed used to initialize the random generator.

    Returns
    -------
    dict[str, numpy.ndarray]
        Mapping from augmentation name to augmented intensity array.
    """
    rng = np.random.default_rng(base_seed)

    return {
        "noise": add_noise(intensity, rng),
        "baseline": baseline_drift(wavenumbers, intensity, rng),
        "scaled": scale_intensity(intensity, rng),
        "shifted": shift_spectrum(wavenumbers, intensity, rng),
        "broadened": broaden_peaks(intensity, rng),
        "kumaraswamy": kumaraswamy_warp(wavenumbers, intensity, rng),
    }


# -------------------------------------------------
# DATAFRAME AUGMENTATION
# -------------------------------------------------
def augment_raman_dataframe(df):
    """Augment Raman spectra stored in a DataFrame.

    Parameters
    ----------
    df : pandas.DataFrame
        DataFrame containing Raman spectra in `Wavenumbers` and `Intensities`
        columns together with metadata columns.

    Returns
    -------
    pandas.DataFrame
        DataFrame with original rows plus generated augmented rows.
    """

    augmented_rows = []

    mask = (
        (df["Typ_zeba"].str.lower() != "zdrowe")
        & (df["ID_zeba"] != "042")
        & (df["Typ_zeba"] != "Chore_sztucznie")
    )

    df_original = df.copy()
    df_original["augmentation_type"] = "original"

    for idx, row in df[mask].iterrows():
        wn = np.array(row["Wavenumbers"])
        intensity = np.array(row["Intensities"])

        # Deterministic seed per row
        row_seed = GLOBAL_SEED + hash((row["ID_zeba"], row["ID_skanu"])) % 10_000

        augmented = augment_spectrum(wn, intensity, row_seed)

        for aug_type, aug_intensity in augmented.items():
            new_row = row.copy()
            new_row["Intensities"] = aug_intensity.tolist()
            new_row["augmentation_type"] = aug_type
            augmented_rows.append(new_row)

    df_augmented = pd.DataFrame(augmented_rows)

    df_final = pd.concat([df_original, df_augmented], ignore_index=True)
    df_final = df_final.reset_index(drop=True)

    return df_final


# Execution of the program starts here
if __name__ == "__main__":

    print("Augmentating data...")
    root = find_project_root()
    data_dir = os.path.join(root, "Data")

    input_path = os.path.join(data_dir, "scans_nonaugmented.parquet")
    output_path = os.path.join(data_dir, "scans_augmented.parquet")

    df = pd.read_parquet(input_path, engine="pyarrow")

    df_augmented = augment_raman_dataframe(df)

    df_augmented.to_parquet(output_path, engine="pyarrow", index=False)

    print("Augmentation complete.")