"""
Data cleaning script for Raman spectra.
Reads the augmented and non-augmented parquet files generated by previous steps,
filters spectra to those covering the full wavenumber range of 900-990 cm^-1,
and expands the `Intensities` column into individual columns for each wavenumber.

Expected input files
-----------------
- scans_augmented.parquet     (raw, has Wavenumbers/Intensities columns)
- scans_nonaugmented.parquet  (raw, has Wavenumbers/Intensities columns)

Expected output files
-----------------
- scans_clean_augmented.parquet     (cleaned, has augmentation_type column)
- scans_clean_nonaugmented.parquet  (cleaned, no augmentation_type column)

Notes
-----
- The script will automatically skip processing if the output files already exist.
- The cleaning process includes:
  1. Filtering spectra to those that cover the full wavenumber range of 900-990 cm^-1.
  2. Merging duplicate wavenumbers by averaging their intensities.
  3. Filling in missing wavenumbers within the range by linear interpolation.
  4. Expanding the `Intensities` column into separate columns named `intensity_at_<wavenumber>`.
"""

import os
import numpy as np
import pandas as pd
from tqdm import tqdm
from ..Utils.utils import find_project_root

# cleaning logic:
def clean_df_range(df, minv, maxv):
    """Clean spectra and expand intensities to fixed wavenumber columns.

    Parameters
    ----------
    df : pandas.DataFrame
        Input DataFrame with `Wavenumbers` and `Intensities` columns.
    minv : int
        Lower bound of the target wavenumber range (inclusive).
    maxv : int
        Upper bound of the target wavenumber range (inclusive).

    Returns
    -------
    pandas.DataFrame
        DataFrame where each wavenumber in `[minv, maxv]` is represented by
        one `intensity_at_<wavenumber>` column.
    """

    waves = np.array(df["Wavenumbers"], dtype=object)

    df["minimum"] = [np.min(arr) for arr in waves]
    df["maximum"] = [np.max(arr) for arr in waves]

    # Keep only spectra covering full range
    df = df[(df["minimum"] < minv + 1) & (df["maximum"] > maxv - 1)].copy()

    lengths = np.array(df["Wavenumbers"], dtype=object)
    intensities = np.array(df["Intensities"], dtype=object)

    lengths = np.array([np.round(x) for x in lengths], dtype=object)

    # Mask range
    mask = [((x >= minv) & (x <= maxv)) for x in lengths]
    lengths = [x[m] for x, m in zip(lengths, mask)]
    intensities = [y[m] for y, m in zip(intensities, mask)]

    # Merge duplicates
    new_lengths, new_intensities = [], []

    for L, I in tqdm(zip(lengths, intensities), total=len(lengths)):
        idx = np.argsort(L)[::-1]
        L_sorted, I_sorted = L[idx], I[idx]

        merged_L, merged_I = [], []
        i = 0
        while i < len(L_sorted):
            j = i + 1
            while j < len(L_sorted) and L_sorted[j] == L_sorted[i]:
                j += 1
            merged_L.append(L_sorted[i])
            merged_I.append(np.mean(I_sorted[i:j]))
            i = j

        new_lengths.append(np.array(merged_L))
        new_intensities.append(np.array(merged_I))

    # Fill gaps
    new_lengths_filled, new_intensities_filled = [], []

    for L, I in tqdm(zip(new_lengths, new_intensities), total=len(new_lengths)):
        full_L = np.arange(minv, maxv + 1)
        full_I = np.zeros_like(full_L, dtype=float)

        L_sorted_idx = np.argsort(L)
        L_sorted, I_sorted = L[L_sorted_idx], I[L_sorted_idx]

        l_idx = 0
        for i, val in enumerate(full_L):
            if l_idx < len(L_sorted) and val == L_sorted[l_idx]:
                full_I[i] = I_sorted[l_idx]
                l_idx += 1
            else:
                prev_val = full_I[i - 1] if i > 0 else I_sorted[0]
                next_val = I_sorted[l_idx] if l_idx < len(I_sorted) else I_sorted[-1]
                full_I[i] = (prev_val + next_val) / 2

        new_lengths_filled.append(full_L)
        new_intensities_filled.append(full_I)

    intensities_2d = np.stack(new_intensities_filled)
    lengths_2d = np.stack(new_lengths_filled)

    # Expand to columns
    for i, arr in enumerate(intensities_2d.T):
        df[f"intensity_at_{lengths_2d[0][i]}"] = arr

    df = df.drop(
        columns=["Wavenumbers", "Intensities", "minimum", "maximum"],
        errors="ignore",
    )

    return df


# Execution of the program starts here
if __name__ == "__main__":

    print("starting cleaning data")
    root = find_project_root()
    data_dir = os.path.join(root, "Data")

    minv, maxv = 900, 990

    aug_path = os.path.join(data_dir, "scans_augmented.parquet")
    nonaug_path = os.path.join(data_dir, "scans_nonaugmented.parquet")

    df_aug = pd.read_parquet(aug_path, engine="pyarrow")
    df_nonaug = pd.read_parquet(nonaug_path, engine="pyarrow")

    df_clean_aug = clean_df_range(df_aug, minv, maxv)
    df_clean_nonaug = clean_df_range(df_nonaug, minv, maxv)

    print("cleaning augmented data")
    df_clean_aug.to_parquet(
        os.path.join(data_dir, "scans_clean_augmented.parquet"),
        engine="pyarrow",
        index=False,
    )

    print("cleaning nonaugmented data")
    df_clean_nonaug.to_parquet(
        os.path.join(data_dir, "scans_clean_nonaugmented.parquet"),
        engine="pyarrow",
        index=False,
    )

    print("Cleaning complete.")