"""
This module defines a function to run the complete data processing pipeline 
for the tooth decay project. It checks for the existence of intermediate files 
and executes missing steps in sequence: raw-to-parquet conversion, augmentation, 
and cleaning. The pipeline can be forced to run all steps regardless of existing files 
using a command-line argument --all.
The expected data files and their generation steps are as follows:
- `scans_nonaugmented.parquet`: Generated by `buchwald_data_2_parquet.py` from raw text scans.
- `scans_augmented.parquet`: Generated by `data_augmentation.py` from `scans_nonaugmented.parquet`.
- `scans_clean_augmented.parquet` and `scans_clean_nonaugmented.parquet`: 
    Generated by `data_cleaning.py` from the respective augmented and non-augmented parquet files.
"""

import os
import sys
import subprocess
import argparse
from ..Utils.utils import find_project_root


def run_script(module_name, working_dir):
    """Run a Python module as a subprocess.

    Parameters
    ----------
    module_name : str
        Fully qualified module path to run, e.g.
        `FixedToothDecayProject.Data_Scripts.buchwald_data_2_parquet`.
    working_dir : str
        Working directory used for subprocess execution.

    Returns
    -------
    None
    """
    print(f"\n Running module: {module_name}")
    subprocess.run(
        [sys.executable, "-m", module_name],
        check=True,
        cwd=working_dir,
    )


def main(force_all=False):
    """Run the complete data processing pipeline.

    The function checks for intermediate files and executes missing steps in
    sequence: raw-to-parquet conversion, augmentation, and cleaning.

    Parameters
    ----------
    force_all : bool, default=False
        If True, executes all steps regardless of whether output files exist.

    Returns
    -------
    None
    """

    root = find_project_root()
    data_dir = os.path.join(root, "Data")
    workspace_dir = os.path.dirname(root)
    data_scripts_package = __package__ or f"{os.path.basename(root)}.Data_Scripts"

    teeth_dir = os.path.join(data_dir, "teeth_ordered_data")

    scans_nonaug = os.path.join(data_dir, "scans_nonaugmented.parquet")
    scans_aug = os.path.join(data_dir, "scans_augmented.parquet")
    scans_clean_aug = os.path.join(data_dir, "scans_clean_augmented.parquet")
    scans_clean_nonaug = os.path.join(data_dir, "scans_clean_nonaugmented.parquet")

    # Required script modules
    script_buchwald = f"{data_scripts_package}.buchwald_data_2_parquet"
    script_aug = f"{data_scripts_package}.data_augmentation"
    script_clean = f"{data_scripts_package}.data_cleaning"

    sth_missing = 0 # if any step is missing, this will be set to 1 and all following steps will be run to ensure consistency. If all files are present, this remains 0 and all steps are skipped.
    # Check raw data folder
    if not os.path.exists(teeth_dir) or sth_missing == 1:
        print("No teeth_ordered_data found. Nothing can be done.")
        sth_missing = 1
        return

    # Step 1 — Generate nonaugmented parquet
    if force_all or not os.path.exists(scans_nonaug) or sth_missing == 1:
        run_script(script_buchwald, workspace_dir)
        sth_missing = 1

    else:
        print("✔ scans_nonaugmented.parquet exists — skipping.")

    # Step 2 — Augmentation
    if force_all or not os.path.exists(scans_aug) or sth_missing == 1:
        run_script(script_aug, workspace_dir)
        sth_missing = 1
    else:
        print("✔ scans_augmented.parquet exists — skipping.")

    # Step 3 — Cleaning
    clean_missing = (
        not os.path.exists(scans_clean_aug)
        or not os.path.exists(scans_clean_nonaug)
    )

    if force_all or clean_missing or sth_missing == 1:
        run_script(script_clean, workspace_dir)
        sth_missing = 1
    else:
        print("✔ Clean parquet files exist — skipping.")

    print("\nPipeline finished.")


# Execution of the program starts here
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run data processing pipeline.")
    parser.add_argument(
        "--all",
        action="store_true",
        help="Force run all steps (ignore existing files)",
    )

    args = parser.parse_args()

    main(force_all=args.all)


# to run all use:
#  python -m FixedToothDecayProject.Data_Scripts.run_pipeline --all